Abstract module names (\$modulename). Add easy lookup functions (ldap_search_getattr) and convert code to use it. Add chsh code.

diff --git a/diradm b/diradm
--- a/diradm
+++ b/diradm
@@ -5,7 +5,7 @@
 # diradm:	A tool for managing posix users and groups in a LDAP directory.
 #		It uses ldap[add|modify|delete] from the OpenLDAP project.
 #
-# Version:	$Header: /code/convert/cvsroot/infrastructure/diradm/Attic/diradm,v 1.2 2003/07/12 10:52:56 robbat2 Exp $
+# Version:	$Header: /code/convert/cvsroot/infrastructure/diradm/Attic/diradm,v 1.3 2003/07/12 10:55:33 robbat2 Exp $
 #
 # Copyright (C) 2003  Daniel Himler  <dan@hits.at>
 #
@@ -143,6 +143,17 @@ print_version () {
 	echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
 }
 
+# eg: 
+# ldap_search_getattr "$GROUPBASE" "gidNumber=100" cn
+# (returns 'users' on systems with that initial data in LDAP)
+ldap_search_getattr() {
+	basedn="${1}"
+	search="${2}"
+	attr="${3}"
+	regex="^${attr}:{1,2} "
+	$LDAPSEARCH -b "${basedn}" "${search}" ${attr} | egrep "${regex}" | sed -re "s/${regex}//"
+}
+
 search_user () {
 	$LDAPSEARCH -b "$USERBASE" "$1=$2" | grep -qs "^$1: $2$"
 	return "$?"
@@ -154,6 +165,7 @@ search_group () {
 }
 
 useradd () {
+	[ -z "${modulename}" ] && modulename="useradd"
 	while getopts "u:og:G:h:d:s:c:mk:f:e:p:" OPTION; do
 		case "$OPTION" in
 			u) UIDNUMBER="$OPTARG";;
@@ -181,24 +193,24 @@ useradd () {
 	fi
 	echo "$LOGIN" | grep -qs "^[[:alnum:]]*$"
 	if [ "$?" -ne 0 ]; then
-		echo "useradd: Invalid user name \"$LOGIN\""
+		echo "${modulename}: Invalid user name \"$LOGIN\""
 		exit 3
 	else
 		search_user "uid" "$LOGIN"
 		if [ "$?" -eq 0 ]; then
-			echo "useradd: User \"$LOGIN\" exists"
+			echo "${modulename}: User \"$LOGIN\" exists"
 			exit 9
 		fi
 	fi
 	if [ -n "$UIDNUMBER" ]; then
 		echo "$UIDNUMBER" | grep -qs "^[[:digit:]]*$"
 		if [ "$?" -ne 0 ]; then
-			echo "useradd: Invalid numeric argument \"$UIDNUMBER\""
+			echo "${modulename}: Invalid numeric argument \"$UIDNUMBER\""
 			exit 3
 		fi
 		search_user "uidNumber" "$UIDNUMBER"
 		if [ "$?" -eq 0 -a "$DUPLICATES" != "yes" ]; then
-			echo "useradd: uid $UIDNUMBER is not unique"
+			echo "${modulename}: uid $UIDNUMBER is not unique"
 			exit 4
 		fi
 	else
@@ -214,9 +226,10 @@ useradd () {
 		if [ "$?" -eq 0 ]; then
 			GIDNUMBER="$GID"
 		else
-			GIDNUMBER="$($LDAPSEARCH -b "$GROUPBASE" "cn=$GID" | grep "gidNumber: " | sed "s/gidNumber: //")"
+			#GIDNUMBER="$($LDAPSEARCH -b "$GROUPBASE" "cn=$GID" | grep "gidNumber: " | sed "s/gidNumber: //")"
+			GIDNUMBER="$(ldap_search_getattr "$GROUPBASE" "cn=$GID" gidNumber)"
 			if [ -z "$GIDNUMBER" ]; then
-				echo "useradd: Unknown group \"$GID\""
+				echo "${modulename}: Unknown group \"$GID\""
 				exit 6
 			fi
 		fi
@@ -225,7 +238,7 @@ useradd () {
 	fi
 	search_group "gidNumber" "$GIDNUMBER"
 	if [ "$?" -ne 0 ]; then
-		echo "useradd: Warning! Group $GIDNUMBER not found. Adding user anyway."
+		echo "${modulename}: Warning! Group $GIDNUMBER not found. Adding user anyway."
 	fi
 	if [ -n "$OTHERGROUPS" ]; then
 		OTHERGROUPS="${OTHERGROUPS//,/ }"
@@ -234,17 +247,18 @@ useradd () {
 			if [ "$?" -eq 0 ]; then
 				search_group "gidNumber" "$POSIXGROUP"
 				if [ "$?" -ne 0 ]; then
-					echo "useradd: Unknown group \"$POSIXGROUP\""
+					echo "${modulename}: Unknown group \"$POSIXGROUP\""
 					exit 6
 				fi
-				POSIXGROUP="$($LDAPSEARCH -b "$GROUPBASE" "gidNumber=$POSIXGROUP" |
-					grep "^cn:" |
-					sed "s/cn: //")"
+				#POSIXGROUP="$($LDAPSEARCH -b "$GROUPBASE" "gidNumber=$POSIXGROUP" |
+				#	grep "^cn:" |
+				#	sed "s/cn: //")"
+				POSIXGROUP="$(ldap_search_getattr "$GROUPBASE" "gidNumber=$POSIXGROUP" cn)"
 				ADDTOGROUPS="$ADDTOGROUPS $POSIXGROUP"
 			else
 				search_group "cn" "$POSIXGROUP"
 				if [ "$?" -ne 0 ]; then
-					echo "useradd: Unknown group \"$POSIXGROUP\""
+					echo "${modulename}: Unknown group \"$POSIXGROUP\""
 					exit 6
 				fi
 				ADDTOGROUPS="$ADDTOGROUPS $POSIXGROUP"
@@ -261,24 +275,24 @@ useradd () {
 	[ -z "$HOMEDIRECTORY" ] && HOMEDIRECTORY="$HOMEBASE/$LOGIN"
 	echo "$HOMEDIRECTORY" | grep -qs "^/"
 	if [ "$?" -ne 0 ]; then
-		echo "useradd: Invalid home directory \"$HOMEDIRECTORY\""
+		echo "${modulename}: Invalid home directory \"$HOMEDIRECTORY\""
 		exit 3
 	fi
 	[ -z "$LOGINSHELL" ] && LOGINSHELL="$DEFAULT_LOGINSHELL"
 	echo "$LOGINSHELL" | grep -qs "^/"
 	if [ "$?" -ne 0 ]; then
-		echo "useradd: Invalid shell \"$LOGINSHELL\""
+		echo "${modulename}: Invalid shell \"$LOGINSHELL\""
 		exit 3
 	fi
 	[ -z "$COMMENT" ] && COMMENT="$LOGIN"
 	if [ -n "$HOMEDIRECTORY" -a "$CREATEHOMEDIR" = "yes" ]; then
 		if [ "$(whoami)" != "root" ]; then
-			echo "useradd: Only root may create home directories"
+			echo "${modulename}: Only root may create home directories"
 			exit 12
 		fi
 		PARENTDIR="$(dirname "$HOMEDIRECTORY")"
 		if [ ! -w "$PARENTDIR" ]; then
-			echo "useradd: Cannot create directory \"$HOMEDIRECTORY\""
+			echo "${modulename}: Cannot create directory \"$HOMEDIRECTORY\""
 			exit 12
 		fi
 	fi
@@ -286,7 +300,7 @@ useradd () {
 	if [ "$SHADOWINACTIVE" != "-1" ]; then
 		echo "$SHADOWINACTIVE" | grep -qs "^[[:digit:]]*$"
 		if [ "$?" -ne 0 ]; then
-			echo "useradd: Invalid numeric argument \"$SHADOWINACTIVE\""
+			echo "${modulename}: Invalid numeric argument \"$SHADOWINACTIVE\""
 			exit 3
 		fi
 	fi
@@ -294,7 +308,7 @@ useradd () {
 	if [ "$SHADOWEXPIRE" != "-1" ]; then
 		echo "$SHADOWEXPIRE" | grep -qs "^[[:digit:]]\{4\}-[[:digit:]]\{2\}-[[:digit:]]\{2\}$"
 		if [ "$?" -ne 0 ]; then
-			echo "useradd: Invalid date \"$SHADOWEXPIRE\""
+			echo "${modulename}: Invalid date \"$SHADOWEXPIRE\""
 			exit 3
 		else
 			let SHADOWEXPIRE="$(date -d "$SHADOWEXPIRE" +%s) / 86400"
@@ -325,7 +339,8 @@ $HOSTS
 EOF
 	) | $LDAPADD > /dev/null
 	if [ -n "$ADDTOGROUPS" ]; then
-		DELETEFROMGROUPS="$($LDAPSEARCH -b "$GROUPBASE" "memberUid=$LOGIN" | grep "^cn:" | sed "s/^cn: //")"
+		#DELETEFROMGROUPS="$($LDAPSEARCH -b "$GROUPBASE" "memberUid=$LOGIN" | grep "^cn:" | sed "s/^cn: //")"
+		DELETEFROMGROUPS="$(ldap_search_getattr "$GROUPBASE" "memberUid=$LOGIN" cn)"
 		for POSIXGROUP in $DELETEFROMGROUPS; do
 			COMMAND="$COMMAND\ndn: cn=$POSIXGROUP,$GROUPBASE\ndelete: memberUid\nmemberUid: $LOGIN\n"
 		done
@@ -343,8 +358,9 @@ EOF
 }
 
 usermod () {
+	[ -z "${modulename}" ] && modulename="usermod"
 	if [ "$#" -le 1 ]; then
-		echo "usermod: No flags given"
+		echo "${modulename}: No flags given"
 		exit 2
 	fi
 	while getopts "u:og:G:h:d:s:c:l:mf:e:p:LU" OPTION; do
@@ -376,18 +392,18 @@ usermod () {
 	fi
 	search_user "uid" "$LOGIN"
 	if [ "$?" -ne 0 ]; then
-		echo "usermod: User \"$LOGIN\" does not exist"
+		echo "${modulename}: User \"$LOGIN\" does not exist"
 		exit 6
 	fi
 	if [ -n "$UIDNUMBER" ]; then
 		echo "$UIDNUMBER" | grep -qs "^[[:digit:]]*$"
 		if [ "$?" -ne 0 ]; then
-			echo "usermod: Invalid numeric argument \"$UIDNUMBER\""
+			echo "${modulename}: Invalid numeric argument \"$UIDNUMBER\""
 			exit 3
 		fi
 		search_user "uidNumber" "$UIDNUMBER"
 		if [ "$?" -eq 0 -a "$DUPLICATES" != "yes" ]; then
-			echo "usermod: uid $UIDNUMBER is not unique"
+			echo "${modulename}: uid $UIDNUMBER is not unique"
 			exit 4
 		fi
 	fi
@@ -396,15 +412,16 @@ usermod () {
 		if [ "$?" -eq 0 ]; then
 			GIDNUMBER="$GID"
 		else
-			GIDNUMBER="$($LDAPSEARCH -b "$GROUPBASE" "cn=$GID" | grep "gidNumber: " | sed "s/gidNumber: //")"
+			#GIDNUMBER="$($LDAPSEARCH -b "$GROUPBASE" "cn=$GID" | grep "gidNumber: " | sed "s/gidNumber: //")"
+			GIDNUMBER="$(ldap_search_getattr "$GROUPBASE" "cn=$GID" gidNumber)"
 			if [ -z "$GIDNUMBER" ]; then
-				echo "usermod: Unknown group \"$GID\""
+				echo "${modulename}: Unknown group \"$GID\""
 				exit 6
 			fi
 		fi
 		search_group "gidNumber" "$GIDNUMBER"
 		if [ "$?" -ne 0 ]; then
-			echo "useradd: Warning! Group $GIDNUMBER not found. Modifying user anyway."
+			echo "${modulename}: Warning! Group $GIDNUMBER not found. Modifying user anyway."
 		fi
 	fi
 	if [ -n "$OTHERGROUPS" ]; then
@@ -414,17 +431,18 @@ usermod () {
 			if [ "$?" -eq 0 ]; then
 				search_group "gidNumber" "$POSIXGROUP"
 				if [ "$?" -ne 0 ]; then
-					echo "usermod: Unknown other group number \"$POSIXGROUP\""
+					echo "${modulename}: Unknown other group number \"$POSIXGROUP\""
 					exit 6
 				fi
-				POSIXGROUP="$($LDAPSEARCH -b "$GROUPBASE" "gidNumber=$POSIXGROUP" |
-					grep "^cn:" |
-					sed "s/cn: //")"
+				#POSIXGROUP="$($LDAPSEARCH -b "$GROUPBASE" "gidNumber=$POSIXGROUP" |
+				#	grep "^cn:" |
+				#	sed "s/cn: //")"
+				POSIXGROUP="$(ldap_search_getattr "$GROUPBASE" "gidNumber=$POSIXGROUP" cn)"
 				ADDTOGROUPS="$ADDTOGROUPS $POSIXGROUP"
 			else
 				search_group "cn" "$POSIXGROUP"
 				if [ "$?" -ne 0 ]; then
-					echo "usermod: Unknown other group \"$POSIXGROUP\""
+					echo "${modulename}: Unknown other group \"$POSIXGROUP\""
 					exit 6
 				fi
 				ADDTOGROUPS="$ADDTOGROUPS $POSIXGROUP"
@@ -441,52 +459,54 @@ usermod () {
 	if [ -n "$HOMEDIRECTORY" ]; then
 		echo "$HOMEDIRECTORY" | grep -qs "^/"
 		if [ "$?" -ne 0 ]; then
-			echo "usermod: Invalid home directory \"$HOMEDIRECTORY\""
+			echo "${modulename}: Invalid home directory \"$HOMEDIRECTORY\""
 			exit 3
 		fi
 	fi
 	if [ -n "$LOGINSHELL" ]; then
 		echo "$LOGINSHELL" | grep -qs "^/"
 		if [ "$?" -ne 0 ]; then
-			echo "usermod: Invalid shell \"$LOGINSHELL\""
+			echo "${modulename}: Invalid shell \"$LOGINSHELL\""
 			exit 3
 		fi
 	fi
 	if [ -n "$NEWLOGIN" ]; then
 		echo "$NEWLOGIN" | grep -qs "^[[:alnum:]]*$"
 		if [ "$?" -ne 0 ]; then
-			echo "usermod: Invalid user name \"$NEWLOGIN\""
+			echo "${modulename}: Invalid user name \"$NEWLOGIN\""
 			exit 3
 		else
 			search_user "uid" "$NEWLOGIN"
 			if [ "$?" -eq 0 ]; then
-				echo "usermod: User \"$NEWLOGIN\" exists"
+				echo "${modulename}: User \"$NEWLOGIN\" exists"
 				exit 9
 			fi
 		fi
 		if [ -z "$ADDTOGROUPS" ]; then
-			ADDTOGROUPS="$($LDAPSEARCH -b "$GROUPBASE" "memberUid=$LOGIN" | grep "^cn:" | sed "s/^cn: //")"
+			#ADDTOGROUPS="$($LDAPSEARCH -b "$GROUPBASE" "memberUid=$LOGIN" | grep "^cn:" | sed "s/^cn: //")"
+			ADDTOGROUPS="$(ldap_search_getattr "$GROUPBASE" "memberUid=$LOGIN" cn)"
 		fi
 	fi
 	if [ -n "$HOMEDIRECTORY" -a "$MOVEHOMEDIR" = "yes" ]; then
 		if [ "$(whoami)" != "root" ]; then
-			echo "usermod: Only root may move home directories"
+			echo "${modulename}: Only root may move home directories"
 			exit 12
 		fi
 		PARENTDIR="$(dirname "$HOMEDIRECTORY")"
 		if [ ! -w "$PARENTDIR" ]; then
-			echo "usermod: Cannot create directory \"$HOMEDIRECTORY\""
+			echo "${modulename}: Cannot create directory \"$HOMEDIRECTORY\""
 			exit 12
 		fi
-		OLDHOMEDIRECTORY="$($LDAPSEARCH -b "$USERBASE" "uid=$LOGIN" |
-			grep "^homeDirectory:" |
-			sed "s/^homeDirectory: //")"
+		#OLDHOMEDIRECTORY="$($LDAPSEARCH -b "$USERBASE" "uid=$LOGIN" |
+		#	grep "^homeDirectory:" |
+		#	sed "s/^homeDirectory: //")"
+		OLDHOMEDIRECTORY="$(ldap_search_getattr "$USERBASE" "uid=$LOGIN" homeDirectory)"
 	fi
 	if [ -n "$SHADOWINACTIVE" ]; then
 		if [ "$SHADOWINACTIVE" != "-1" ]; then
 			echo "$SHADOWINACTIVE" | grep -qs "^[[:digit:]]*$"
 			if [ "$?" -ne 0 ]; then
-				echo "usermod: Invalid numeric argument \"$SHADOWINACTIVE\""
+				echo "${modulename}: Invalid numeric argument \"$SHADOWINACTIVE\""
 				exit 3
 			fi
 		fi
@@ -495,7 +515,7 @@ usermod () {
 		if [ "$SHADOWEXPIRE" != "-1" ]; then
 			echo "$SHADOWEXPIRE" | grep -qs "^[[:digit:]]\{4\}-[[:digit:]]\{2\}-[[:digit:]]\{2\}$"
 			if [ "$?" -ne 0 ]; then
-				echo "usermod: Invalid date \"$SHADOWEXPIRE\""
+				echo "${modulename}: Invalid date \"$SHADOWEXPIRE\""
 				exit 3
 			else
 				let SHADOWEXPIRE="$(date -d "$SHADOWEXPIRE" +%s) / 86400"
@@ -503,9 +523,10 @@ usermod () {
 		fi
 	fi
 	if [ -n "$LOCKED" ]; then
-		OLDPASSWORD="$(ldapsearch $ADMINOPTIONS -b "$USERBASE" "uid=$LOGIN" |
-			grep "^userPassword::" |
-			sed "s/^userPassword:: //")"
+		#OLDPASSWORD="$(ldapsearch $ADMINOPTIONS -b "$USERBASE" "uid=$LOGIN" |
+		#	grep "^userPassword::" |
+		#	sed "s/^userPassword:: //")"
+		OLDPASSWORD="$(ldap_search_getattr "$USERBASE" "uid=$LOGIN" userPassword)"
 		if [ "$LOCKED" = "yes" ]; then
 			USERPASSWORD="!$OLDPASSWORD"
 		elif [ "$LOCKED" = "no" ]; then
@@ -525,7 +546,8 @@ usermod () {
 	[ "$COMMAND" = "dn: uid=$LOGIN,$USERBASE\n" ] && unset COMMAND
 	[ -n "$NEWLOGIN" ] && COMMAND="${COMMAND}\ndn: uid=$LOGIN,$USERBASE\nchangetype: modrdn\nnewrdn: uid=$NEWLOGIN\n"
 	if [ -n "$ADDTOGROUPS" ]; then
-		DELETEFROMGROUPS="$($LDAPSEARCH -b "$GROUPBASE" "memberUid=$LOGIN" | grep "^cn:" | sed "s/^cn: //")"
+		#DELETEFROMGROUPS="$($LDAPSEARCH -b "$GROUPBASE" "memberUid=$LOGIN" | grep "^cn:" | sed "s/^cn: //")"
+		DELETEFROMGROUPS="$(ldap_search_getattr "$GROUPBASE" "memberUid=$LOGIN" cn)"
 		for POSIXGROUP in $DELETEFROMGROUPS; do
 			COMMAND="$COMMAND\ndn: cn=$POSIXGROUP,$GROUPBASE\ndelete: memberUid\nmemberUid: $LOGIN\n"
 		done
@@ -543,6 +565,7 @@ usermod () {
 }
 
 userdel () {
+	[ -z "${modulename}" ] && modulename="userdel"
 	while getopts "r" OPTION; do
 		case "$OPTION" in
 			r) REMOVEHOMEDIR="yes";;
@@ -558,23 +581,26 @@ userdel () {
 	fi
 	search_user "uid" "$LOGIN"
 	if [ "$?" -ne 0 ]; then
-		echo "userdel: User \"$LOGIN\" does not exist"
+		echo "${modulename}: User \"$LOGIN\" does not exist"
 		exit 6
 	fi
 	if [ "$REMOVEHOMEDIR" = "yes" ]; then
 		if [ "$(whoami)" != "root" ]; then
-			echo "userdel: Only root may remove home directories"
+			echo "${modulename}: Only root may remove home directories"
 			exit 12
 		fi
-		HOMEDIRECTORY="$($LDAPSEARCH -b "$USERBASE" "uid=$LOGIN" |
-			grep "^homeDirectory:" |
-			sed "s/^homeDirectory: //")"
-		UIDNUMBER="$($LDAPSEARCH -b "$USERBASE" "uid=$LOGIN" |
-			grep "^uidNumber:" |
-			sed "s/^uidNumber: //")"
+		#HOMEDIRECTORY="$($LDAPSEARCH -b "$USERBASE" "uid=$LOGIN" |
+		#	grep "^homeDirectory:" |
+		#	sed "s/^homeDirectory: //")"
+		HOMEDIRECTORY="$(ldap_search_getattr "$USERBASE" "uid=$LOGIN" homeDirectory)"
+		#UIDNUMBER="$($LDAPSEARCH -b "$USERBASE" "uid=$LOGIN" |
+		#	grep "^uidNumber:" |
+		#	sed "s/^uidNumber: //")"
+		UIDNUMBER="$(ldap_search_getattr "$USERBASE" "uid=$LOGIN" uidNumber)"
 	fi
 	COMMAND="dn: uid=$LOGIN,$USERBASE\nchangetype: delete\n"
-	DELETEFROMGROUPS="$($LDAPSEARCH -b "$GROUPBASE" "memberUid=$LOGIN" | grep "^cn:" | sed "s/^cn: //")"
+	#DELETEFROMGROUPS="$($LDAPSEARCH -b "$GROUPBASE" "memberUid=$LOGIN" | grep "^cn:" | sed "s/^cn: //")"
+	DELETEFROMGROUPS="$(ldap_search_getattr "$GROUPBASE" "memberUid=$LOGIN" cn)"
 	for POSIXGROUP in $DELETEFROMGROUPS; do
 		COMMAND="$COMMAND\ndn: cn=$POSIXGROUP,$GROUPBASE\ndelete: memberUid\nmemberUid: $LOGIN\n"
 	done
@@ -586,13 +612,14 @@ userdel () {
 		if [ "$UIDNUMBER" -eq "$OWNER_UIDNUMBER" ]; then
 			rm -rf "$HOMEDIRECTORY"
 		else
-			echo "userdel: $HOMEDIRECTORY not owned by user \"$LOGIN\", not removing"
+			echo "${modulename}: $HOMEDIRECTORY not owned by user \"$LOGIN\", not removing"
 			exit 12
 		fi
 	fi
 }
 
 groupadd () {
+	[ -z "${modulename}" ] && modulename="groupadd"
 	while getopts "g:o" OPTION; do
 		case "$OPTION" in
 			g) GIDNUMBER="$OPTARG";;
@@ -609,24 +636,24 @@ groupadd () {
 	fi
 	echo "$CN" | grep -qs "^[[:alnum:]]*$"
 	if [ "$?" -ne 0 ]; then
-		echo "groupadd: \"$CN\" is not a valid group name"
+		echo "${modulename}: \"$CN\" is not a valid group name"
 		exit 3
 	else
 		search_group "cn" "$CN"
 		if [ "$?" -eq 0 ]; then
-			echo "groupadd: Group \"$CN\" exists"
+			echo "${modulename}: Group \"$CN\" exists"
 			exit 9
 		fi
 	fi
 	if [ -n "$GIDNUMBER" ]; then
 		echo "$GIDNUMBER" | grep -qs "^[[:digit:]]*$"
 		if [ "$?" -ne 0 ]; then
-			echo "groupadd: Invalid numeric argument \"$GIDNUMBER\""
+			echo "${modulename}: Invalid numeric argument \"$GIDNUMBER\""
 			exit 2
 		fi
 		search_group "gidNumber" "$GIDNUMBER"
 		if [ "$?" -eq 0 -a "$DUPLICATES" != "yes" ]; then
-			echo "groupadd: gid $GIDNUMBER is not unique"
+			echo "${modulename}: gid $GIDNUMBER is not unique"
 			exit 4
 		fi
 	else
@@ -649,8 +676,9 @@ EOF
 }
 
 groupmod () {
+	[ -z "${modulename}" ] && modulename="groupmod"
 	if [ "$#" -le 1 ]; then
-		echo "groupmod: No flags given"
+		echo "${modulename}: No flags given"
 		exit 2
 	fi
 	while getopts "g:on:" OPTION; do
@@ -670,30 +698,30 @@ groupmod () {
 	fi
 	search_group "cn" "$CN"
 	if [ "$?" -ne 0 ]; then
-		echo "groupmod: Group \"$CN\" does not exist"
+		echo "${modulename}: Group \"$CN\" does not exist"
 		exit 6
 	fi
 	if [ -n "$GIDNUMBER" ]; then
 		echo "$GIDNUMBER" | grep -qs "^[[:digit:]]*$"
 		if [ "$?" -ne 0 ]; then
-			echo "groupmod: Invalid numeric argument \"$GIDNUMBER\""
+			echo "${modulename}: Invalid numeric argument \"$GIDNUMBER\""
 			exit 2
 		fi
 		search_group "gidNumber" "$GIDNUMBER"
 		if [ "$?" -eq 0 -a "$DUPLICATES" != "yes" ]; then
-			echo "groupadd: gid $GIDNUMBER is not unique"
+			echo "${modulename}: gid $GIDNUMBER is not unique"
 			exit 4
 		fi
 	fi
 	if [ -n "$NEWCN" ]; then
 		echo "$NEWCN" | grep -qs "^[[:alnum:]]*$"
 		if [ "$?" -ne 0 ]; then
-			echo "groupmod: \"$NEWCN\" is not a valid group name"
+			echo "${modulename}: \"$NEWCN\" is not a valid group name"
 			exit 3
 		else
 			search_group "cn" "$NEWCN"
 			if [ "$?" -eq 0 ]; then
-				echo "groupmod: \"$NEWCN\" is not a unique name"
+				echo "${modulename}: \"$NEWCN\" is not a unique name"
 				exit 9
 			fi
 		fi
@@ -704,6 +732,7 @@ groupmod () {
 }
 
 groupdel () {
+	[ -z "${modulename}" ] && modulename="groupdel"
 	if [ "$#" -ne 1 ]; then
 		print_usage
 		exit 2
@@ -712,18 +741,66 @@ groupdel () {
 	fi
 	search_group "cn" "$CN"
 	if [ "$?" -ne 0 ]; then
-		echo "groupdel: Group \"$CN\" does not exist"
+		echo "${modulename}: Group \"$CN\" does not exist"
 		exit 6
 	fi
 	$LDAPDELETE "cn=$CN,$GROUPBASE" > /dev/null
 }
 
+grabinteractiveinput() {
+	msg="${1}"
+	setting="${2}"
+	echo -en "${msg}"
+	read userinput
+	userinput="`echo "${userinput}" | sed -re 's/^[[:space:]]*//g;s/[[:space:]]*$//g;'`"
+	eval $setting="${userinput}"
+}
+
+chsh() {
+	[ -z "${modulename}" ] && modulename="chsh"
+	while getopts "s:" OPTION; do
+		case "$OPTION" in
+			s) LOGINSHELL="$OPTARG";;
+		esac
+	done
+	shift $(($OPTIND - 1))
+	if [ "$#" -ne 1 ]; then
+		print_usage
+		exit 2
+	else
+		LOGIN="$1"
+	fi
+
+	OLDLOGINSHELL="getoldshell"
+	if [ -z "${LOGINSHELL}" ]; then
+		msg="Changing the login shell for ${LOGIN}\nEnter the new value, or press return for the default\n\tLogin Shell [${OLDLOGINSHELL}]: "
+		grabinteractiveinput "${msg}" LOGINSHELL
+		[ -z "${LOGINSHELL}" ] && LOGINSHELL="${OLDLOGINSHELL}"
+	fi
+
+	# recursive behaviour is nice...
+	# But we only do the call if they are changing the shell
+	[ "${OLDLOGINSHELL}" != "${LOGINSHELL}" ] && usermod -s "${LOGINSHELL}" "${LOGIN}"
+}
+
 case "$1" in
-	useradd|usermod|userdel|groupadd|groupmod|groupdel)
+	useradd|usermod|userdel|groupadd|groupmod|groupdel|chsh)
 		ACTION="$1"
 		shift 1
 		$ACTION "$@"
 		;;
+		# host - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/hosts.htm#seg3b0sara
+		# network - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/networks_NFS.htm#idx232
+		# protocol - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/protocols.htm#idx546
+		# service - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/services.htm#idx574
+		# rpc - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/rpc.htm#idx286
+		# ether - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/ethers.htm#idx111
+		# netmask - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/netmasks.htm#idx226
+		# netgroup - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/netgroup.htm#xqr310mart
+		# bootparam - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/bootparams.htm#idx32
+		# automount
+		# aliases - http://publib16.boulder.ibm.com/pseries/en_US/files/aixfiles/aliases.htm#idx12
+	
 	--version)
 		print_version
 		exit 0
@@ -739,3 +816,5 @@ case "$1" in
 esac
 
 exit 0
+
+# vim: ts=4 sts=4 noexpandtab sw=4 ft=sh:
