initial changelog by cvs2cl.

diff --git a/src/diradm.in b/src/diradm.in
--- a/src/diradm.in
+++ b/src/diradm.in
@@ -1,5 +1,5 @@
 #!@BASHSH@
-# $Header: /code/convert/cvsroot/infrastructure/diradm/src/diradm.in,v 1.2 2004/12/12 03:03:19 robbat2 Exp $
+# $Header: /code/convert/cvsroot/infrastructure/diradm/src/diradm.in,v 1.3 2004/12/12 07:30:14 robbat2 Exp $
 # vim: ts=4 sts=4 noexpandtab sw=4 ft=sh syntax=sh:
 ################################################################################
 #
@@ -34,6 +34,9 @@ libexecdir="@libexecdir@"
 sbindir="@sbindir@"
 VERSION="@VERSION@"
 
+# for recursive calls
+DIRADM="${0}"
+
 # find the config file
 # 1. look in SYSCONFDIR
 # 2. look in same directory as this script
@@ -49,8 +52,8 @@ fi
 
 ##################### Don't touch anything below this line #####################
 
-REVISION='$Revision: 1.2 $'
-DATE='$Date: 2004/12/12 03:03:19 $'
+REVISION='$Revision: 1.3 $'
+DATE='$Date: 2004/12/12 07:30:14 $'
 # get the stripped versions
 REVISION="${REVISION% *}" ; REVISION="${REVISION/* }"
 DATE="${DATE#* }" ; DATE="${DATE% *}"
@@ -60,7 +63,7 @@ if [ ! -r "${CONFIG}" ]; then
 	exit 1
 fi
 
-DEPENDENCIES="@EGREP@ @LDAPSEARCH@ @LDAPADD@ @LDAPMODIFY@ @LDAPDELETE@ @SED@ @STAT@ @PERL@"
+DEPENDENCIES="@GREP@ @LDAPSEARCH@ @LDAPADD@ @LDAPMODIFY@ @LDAPDELETE@ @SED@ @STAT@ @PERL@"
 
 selftest() {
 	for DEPENDENCY in ${DEPENDENCIES}; do
@@ -254,7 +257,11 @@ print_usage () {
 	list=''
 	[ -n "$1" ] && list="$1"
 	echo "Usage:"
-	[ -z "$list" -o "$list" == "_all" ] && list="useradd _ usermod _ userdel _ groupadd groupmod groupdel _ chsh _ chfn _ chage _ gpasswd _ smbhostadd smbhostdel _ hostadd hostmod hostdel _ _version  _help _"
+	if [ -z "$list" -o "$list" == "_all" ];
+		list="useradd _ usermod _ userdel _ groupadd groupmod groupdel _ chsh _ chfn _ chage _ gpasswd _ hostadd hostmod hostdel"
+		[ "$ENABLE_SAMBA" = "yes" ] && list="${list} _ smbhostadd smbhostdel"
+		list="${list} _ _version _help _"
+	fi
 	for i in $list; do
 		print_usage_sub ${i}
 	done;
@@ -270,6 +277,7 @@ print_version () {
 }
 
 # Call me nuts, I just wrote set functions in shell!
+# -Robin
 set_union() {
 	a="$1"
 	b="$2"
@@ -415,7 +423,7 @@ daysnow() {
 
 useradd () {
 	[ -z "${modulename}" ] && modulename="useradd"
-	while getopts "u:og:G:h:d:s:c:mk:f:e:E:p:Si" OPTION; do
+	while getopts "u:og:G:h:d:s:rRc:mk:f:e:E:p:Si" OPTION; do
 		case "${OPTION}" in
 			u) UIDNUMBER="${OPTARG}";;
 			o) DUPLICATES="yes";;
@@ -426,6 +434,8 @@ useradd () {
 			s) LOGINSHELL="${OPTARG}";;
 			c) COMMENT="${OPTARG}";;
 			m) CREATEHOMEDIR="yes";;
+			r) USERGROUPS="yes";;
+			R) USERGROUPS="no";;
 			k) SKEL="${OPTARG}";;
 			f) SHADOWINACTIVE="${OPTARG}";;
 			e) SHADOWEXPIRE="${OPTARG}";;
@@ -489,7 +499,25 @@ useradd () {
 			fi
 		fi
 	else
-		GIDNUMBER="${DEFAULT_GIDNUMBER}"
+		if [ "$USERGROUPS" = "no" ]; then
+			GIDNUMBER="${DEFAULT_GIDNUMBER}"
+		else
+			# that evil redhat thing of a group for every user
+			## TODO: GROUP	
+			search_group "cn" "${LOGIN}"
+			if [ "$?" -eq 0 ]; then
+				echo "${modulename}: Group '${LOGIN}' already exists!"
+				echo "Pass -R to useradd to disable USERGROUPS usage."
+				echo "And add the user to a group afterwards."
+				exit 9
+			fi
+			${DIRADM} groupadd "${LOGIN}"
+			if [ "$?" -ne 0 ]; then
+				echo "${modulename}: Failed to add group '${LOGIN}'."
+				exit 9
+			fi
+			GIDNUMBER="$(ldap_search_getattr "${GROUPBASE}" "cn=${LOGIN}" gidNumber)"
+		fi
 	fi
 	search_group "gidNumber" "${GIDNUMBER}"
 	if [ "$?" -ne 0 ]; then
@@ -1624,7 +1652,6 @@ case "${1}" in
 	useradd|usermod|userdel|groupadd|groupmod|groupdel|chsh|chfn|chage|gpasswd|smbhostadd|smbhostdel|hostadd|hostdel|hostmod|selftest)
 		ACTION="${1}"
 		shift 1
-		mkpasswd_resolve
 		${ACTION} "$@"
 		exit 0
 		;;
